name: TestSiteWaldinger
favicon: null
layout_spectrum: 0.7644484422635287
typography_spectrum: 0.7164645660668612
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#585959'
    - '#871e26'
    - '#ced0d0'
    - '#ac646a'
  brandStrength: 0.5625
  lightness: 0.6399669195525348
  saturation: 0.7317069678101689
  rhythmicContrast: 0.421589596895501
purpose: []
